# docs/game_stats_catalog.py

game_stats_catalog = {
    "offense": {
        "overall": {
            "description": "Identifiers, context, composite rates, and fantasy scoring for offensive game logs.",
            "fields": {
                "season": "NFL season (year).",
                "week": "NFL week number.",
                "season_type": "Season type (regular, postseason, etc.).",
                "player_id": "Internal or provider player identifier.",
                "player_name": "Player's full name.",
                "player_display_name": "Official player display name.",
                "position": "Player position (QB/RB/WR/TE, etc.).",
                "position_group": "High-level position group (e.g., QB, RB, WR, TE).",
                "recent_team": "Player's most recent/current team abbreviation.",
                "opponent_team": "Opponent team abbreviation for the game.",
                "headshot_url": "URL to player headshot.",
                "fantasy_points": "Fantasy points (standard scoring for the game).",
                "fantasy_points_ppr": "Fantasy points in PPR scoring for the game.",
                "wopr": "Weighted Opportunity Rating (targets & air yards blend).",
                "racr": "Receiver Air Conversion Ratio (air yards -> receiving yards efficiency).",
                "pacr": "Passing Air Conversion Ratio (air yards -> passing yards efficiency).",
                "dakota": "Composite QB metric blending efficiency signals.",
                "target_share": "Share of team targets in the game.",
                "air_yards_share": "Share of team air yards in the game.",
            },
        },
        "passing": {
            "description": "Passing volume, production, and situational outcomes for the game.",
            "fields": {
                "attempts": "Pass attempts.",
                "completions": "Completed passes.",
                "passing_yards": "Passing yards gained.",
                "passing_tds": "Passing touchdowns.",
                "interceptions": "Interceptions thrown.",
                "passing_first_downs": "First downs gained via pass.",
                "passing_air_yards": "Total intended air yards thrown.",
                "passing_yards_after_catch": "Yards earned after catch by receivers on completed passes.",
                "passing_epa": "Expected points added from passing plays.",
                "passing_2pt_conversions": "Two-point conversions via pass.",
            },
        },
        "rushing": {
            "description": "Rushing volume, production, and ball security for the game.",
            "fields": {
                "carries": "Rushing attempts (carries).",
                "rushing_yards": "Rushing yards gained.",
                "rushing_tds": "Rushing touchdowns.",
                "rushing_first_downs": "First downs gained via rush.",
                "rushing_epa": "Expected points added from rushing plays.",
                "rushing_fumbles": "Fumbles on rushing plays.",
                "rushing_fumbles_lost": "Lost fumbles on rushing plays.",
                "rushing_2pt_conversions": "Two-point conversions via rush.",
            },
        },
        "receiving": {
            "description": "Receiving volume, production, and YAC/air-yards context for the game.",
            "fields": {
                "targets": "Pass targets seen.",
                "receptions": "Receptions made.",
                "receiving_yards": "Receiving yards gained.",
                "receiving_tds": "Receiving touchdowns.",
                "receiving_first_downs": "First downs gained via reception.",
                "receiving_epa": "Expected points added via receiving.",
                "receiving_air_yards": "Air yards on targets to the player.",
                "receiving_yards_after_catch": "Yards after the catch on receptions.",
                "receiving_fumbles": "Fumbles on receptions/after catch.",
                "receiving_fumbles_lost": "Lost fumbles on receptions/after catch.",
                "receiving_2pt_conversions": "Two-point conversions via reception.",
            },
        },
        "pressure_and_sacks": {
            "description": "QB pressure outcomes and ball security on sacks for the game.",
            "fields": {
                "sacks": "Times the player was sacked (for QBs) or credited sacks taken as passer.",
                "sack_yards": "Total yards lost on sacks.",
                "sack_fumbles": "Fumbles occurring on sacks.",
                "sack_fumbles_lost": "Lost fumbles occurring on sacks.",
            },
        },
        "special_teams": {
            "description": "Special-teams related scoring when attributed to the player.",
            "fields": {"special_teams_tds": "Touchdowns scored via special teams (returns/blocks)."},
        },
        "seasonal": {
            "description": "Season-level (aggregated) offensive stats and shares. Unless noted, shares are player share of team total across the season (0-1).",
            "fields": {
                # keys / joins / context
                "player_id": "Internal/provider player identifier used to join IDs.",
                "season": "NFL season (year).",
                "season_type": "Season type (regular, postseason, etc.).",
                "games": "Games played counted in this seasonal aggregation.",
                "name": "Player name from ID join.",
                "position": "Roster position.",
                "team": "Team abbreviation for the season.",
                "merge_name": "Canonical merge key used across sources.",
                # passing volume/production
                "completions": "Season completions.",
                "attempts": "Season pass attempts.",
                "passing_yards": "Season passing yards.",
                "passing_tds": "Season passing touchdowns.",
                "interceptions": "Season interceptions thrown.",
                "sacks": "Times sacked (season).",
                "sack_yards": "Yards lost on sacks (season).",
                "sack_fumbles": "Fumbles on sacks (season).",
                "sack_fumbles_lost": "Lost fumbles on sacks (season).",
                "passing_air_yards": "Intended air yards thrown (season).",
                "passing_yards_after_catch": "Yards after catch on completed passes (season).",
                "passing_first_downs": "First downs via pass (season).",
                "passing_epa": "Total EPA from passing plays (season).",
                "passing_2pt_conversions": "Two-point conversions via pass (season).",
                "pacr": "Passing Air Conversion Ratio (air yards → passing yards efficiency).",
                "dakota": "Composite QB efficiency index for the season.",
                # rushing volume/production
                "carries": "Rushing attempts (season).",
                "rushing_yards": "Rushing yards (season).",
                "rushing_tds": "Rushing TDs (season).",
                "rushing_first_downs": "First downs via rush (season).",
                "rushing_epa": "Total EPA from rushing plays (season).",
                "rushing_fumbles": "Rushing fumbles (season).",
                "rushing_fumbles_lost": "Lost rushing fumbles (season).",
                "rushing_2pt_conversions": "Two-point conversions via rush (season).",
                # receiving volume/production
                "targets": "Targets (season).",
                "receptions": "Receptions (season).",
                "receiving_yards": "Receiving yards (season).",
                "receiving_tds": "Receiving TDs (season).",
                "receiving_first_downs": "First downs via reception (season).",
                "receiving_epa": "Total EPA via receiving (season).",
                "receiving_air_yards": "Air yards on targets to the player (season).",
                "receiving_yards_after_catch": "YAC on receptions (season).",
                "receiving_fumbles": "Fumbles on receptions/after catch (season).",
                "receiving_fumbles_lost": "Lost fumbles on receptions/after catch (season).",
                "receiving_2pt_conversions": "Two-point conversions via reception (season).",
                "racr": "Receiver Air Conversion Ratio (air yards → receiving yards efficiency).",
                # composite / fantasy
                "fantasy_points": "Season fantasy points (standard).",
                "fantasy_points_ppr": "Season fantasy points (PPR).",
                "special_teams_tds": "Special-teams TDs credited for the season.",
                # per-team share metrics (season)
                "target_share": "Share of team targets (season).",
                "air_yards_share": "Share of team air yards (season).",
                "tgt_sh": "Alias: target_share (season).",
                "ay_sh": "Alias: air_yards_share (season).",
                "yac_sh": "Share of team YAC generated (season).",
                "ry_sh": "Share of team rushing yards (season).",
                "rtd_sh": "Share of team rushing TDs (season).",
                "rfd_sh": "Share of team rushing first downs (season).",
                "rtdfd_sh": "Share of team rushing TDs + first downs (season).",
                "ppr_sh": "Share of team PPR fantasy points (season).",
                # opportunity / dominator style metrics
                "wopr_x": "WOPR variant X for season (targets & air yards blend; source-specific calc).",
                "wopr_y": "WOPR variant Y for season (alternative weighting).",
                "dom": "Dominator rating (share of team receiving yards + TDs).",
                "w8dom": "Weighted 8-week dominator (recent-form emphasis).",
                "yptmpa": "Yards per team pass attempt (efficiency vs team passing volume).",
            },
        },
    },
    "defense": {
        "overall": {
            "description": "Identifiers and roster context for defensive game logs.",
            "fields": {
                "season": "NFL season (year).",
                "week": "NFL week number.",
                "season_type": "Season type (regular, postseason, etc.).",
                "player_id": "Internal or provider player identifier.",
                "player_name": "Player's full name.",
                "player_display_name": "Official player display name.",
                "position": "Defensive position (e.g., LB, DB, DL).",
                "position_group": "High-level defensive group.",
                "team": "Player's team abbreviation.",
                "headshot_url": "URL to player headshot.",
            },
        },
        "tackling": {
            "description": "Tackling volume and splits.",
            "fields": {
                "def_tackles": "Total tackles (string from source; may need casting).",
                "def_tackles_solo": "Solo tackles.",
                "def_tackle_assists": "Tackle assists (explicit assist count).",
                "def_tackles_with_assist": "Total tackles including assists (alt label).",
                "def_tackles_for_loss": "Tackles for loss.",
                "def_tackles_for_loss_yards": "Yards lost on tackles for loss.",
            },
        },
        "pressure": {
            "description": "Pass-rush production and disruption.",
            "fields": {
                "def_sacks": "Sacks recorded.",
                "def_sack_yards": "Yards lost on sacks recorded.",
                "def_qb_hits": "Quarterback hits.",
                "def_pass_defended": "Passes defended/broken up (PDs).",
            },
        },
        "coverage": {
            "description": "Ball production and returns after interceptions.",
            "fields": {
                "def_interceptions": "Interceptions made.",
                "def_interception_yards": "Return yards on interceptions.",
                "def_tds": "Defensive touchdowns (any defensive scoring play).",
                "def_safety": "Safeties recorded.",
            },
        },
        "turnovers": {
            "description": "Forced and recovered fumbles (own vs opp stat schemas).",
            "fields": {
                "def_fumbles_forced": "Fumbles forced.",
                "def_fumbles": "Fumbles credited to defender (schema-dependent).",
                "def_fumble_recovery_own": "Own team fumble recoveries.",
                "def_fumble_recovery_yards_own": "Return yards on own-team fumble recoveries.",
                "def_fumble_recovery_opp": "Opponent fumbles recovered.",
                "def_fumble_recovery_yards_opp": "Return yards on opponent fumble recoveries.",
            },
        },
        "penalties": {
            "description": "Penalty counts and yardage attributed to the defender.",
            "fields": {
                "def_penalty": "Penalties committed.",
                "def_penalty_yards": "Penalty yards assessed.",
            },
        },
    },
}
